### ISSUE TITLE
LibreOffice 4.0 Support

### ISSUE THREAD

**Issue by JCook21** [cbosdo/coooder#1]
I've tried to install this plugin in LibreOffice 4.0 but it fails with a Java error. Do you have any plans to add support for LibreOffice 4 and if so do you have any ideas for the timeframe?

Thanks.

**Comment by cbosdo** [comment]
Hi Jeremy,

I have no timeframe for the moment as I'm not actively maintaining coooder these days.... but who knows, I may have receive a patch or take some time to hack one.

**Comment by JCook21** [comment]
Hi Cedric,

Thanks for taking the time to reply and I completely understand. I'll
keep an eye open to see if a patch does get submitted.

**Comment by leomontenegro6** [comment]
On Ubuntu 12.10, using Libreoffice 3.6 and java openjdk 1.6, I'm unable to install Coooder unless I install a deb package from Ubuntu repositories. The package name is "libreoffice-dev", and it needs to be installed this way:

$ sudo apt-get install libreoffice-dev

But on Ubuntu 13.04, using Libreoffice 4.0.2 and java openjdk 1.7, I can install it fine, but nothing happens when I highlight some text and click on the brackets icon. System doesn't show any error java-related. Indeed, no message is showed by the way.

I'll try with openjdk 1.6, or oracle java 1.6/1.7 and see what happens.
